### ISSUE TITLE
Copy-button for grabbing the code quickly

### ISSUE THREAD

**Issue by msiebuhr** [msiebuhr/charcod.es#46]
For those of us no longer spending time in Unixes w. mark-to-copy....

**Comment by Munter** [comment]
This is a very difficult thing to do due to security restrictions. What we could do is hook into the copy/cut event and inject the char into the clipboard then. However that would also override any copying of escaped versions of the char, like html or latex versions

**Comment by msiebuhr** [comment]
Github does seem to have a quite well-functioning copy-button for repository URLs;
![screen shot 2015-02-02 at 12 22 39 2](https://cloud.githubusercontent.com/assets/330611/5999826/462bc94e-aad6-11e4-9d92-93d61ac1d0fe.png)

Couldn't we drop in a library like that?

**Comment by msiebuhr** [comment]
Here we go: http://zeroclipboard.org/

**Comment by Munter** [comment]
Yup. Flash dependency

**Comment by msiebuhr** [comment]
Hey - http://caniuse.com/#feat=clipboard

**Comment by msiebuhr** [comment]
Ping @omichelsen :)

**Comment by msiebuhr** [comment]
Fixed by #49.

Thanks, @omichelsen!
