### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by papandreou** [msiebuhr/charcod.es#58]
https://charcod.es/ works, but complains about the certificate being invalid. It's issued to *.netlify.com -- I thought the site was hosted on github pages?

I ran into this because I'd like to replace the appcache manifest with a generated service worker, but that'll only work with a secure origin.

**Comment by msiebuhr** [comment]
Yup. I tried moving it to netlify, and though I had HTTPs switched off.

 * Easier set-up (as they will somehow run `make build-production` for us and expose that.
 * Cloudflare requires using their DNS-servers, yet GratisDNS doesn't allow me to use anything but theirs.

I've written their support to get things straightened out.

Once the switch is fully done, we should clean up the whole 'checkout of gh-pages inside our regular checkout' and just do a `release`-branch instead.

**Comment by msiebuhr** [comment]
@papandreou - I've invited you to co-admin on Netlify. You should get a mail from them shortly.

**Comment by papandreou** [comment]
@msiebuhr, thanks, I'll check it out! I'm sure @Munter can also help us here, as he has used netlify quite a lot and set up https with it before. He even recently went through a name server change from GratisDNS for assetgraph.org :)

**Comment by msiebuhr** [comment]
Netlify support has re-requested our certificates, and now HTTPS work quite fine.
